import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:ionicons/ionicons.dart';

const signInIcon = Ionicons.log_in_outline;
const signOutIcon = Ionicons.log_out_outline;
const cartIcon = Ionicons.cart_outline;
const cubeIcon = Ionicons.cube_outline;
const uploadIcon = Ionicons.cloud_upload_outline;
const deleteIcon = Ionicons.trash_bin_outline;
const shareIcon = Ionicons.share_social_outline;
const helpIcon = Ionicons.help_circle_outline;
const fourLinesMenuIcon = Ionicons.reorder_four_outline;
const puzzleIcon = Ionicons.extension_puzzle_outline;
const repairIcon = Ionicons.build_outline;
const cogIcon = Ionicons.cog_outline;
const customIcon = Ionicons.finger_print_outline;
const starIcon = Ionicons.star_half_outline;
const tickIcon = Ionicons.checkmark_outline;
const tickInABoxIcon = Ionicons.checkbox_outline;
const bulbIcon = Ionicons.bulb_outline;
const alertIcon = Ionicons.alert_circle_outline;
const applicationXIcon = Ionicons.logo_twitter;
const facebookIcon = Ionicons.logo_facebook;
const instagramIcon = Ionicons.logo_instagram;
const linkedInIcon = Ionicons.logo_linkedin;
const tiktokIcon = Ionicons.logo_tiktok;
const redditIcon = Ionicons.logo_reddit;
const turkishLiraIcon = FontAwesomeIcons.turkishLiraSign;
const lockIcon = Ionicons.lock_closed;
const arrowUpIcon = Ionicons.arrow_up_outline;
const homeIcon = Ionicons.home_outline;
