// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD34PKHor64A9OYEBStYoeeJTrxD7ImZEk',
    appId: '1:1014202871879:web:6be7028d4fcc008d994162',
    messagingSenderId: '1014202871879',
    projectId: 'mayda-nozzle',
    authDomain: 'mayda-nozzle.firebaseapp.com',
    storageBucket: 'mayda-nozzle.appspot.com',
    measurementId: 'G-MVGRCXV45K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyMqgonwcsN8Fj781HM-UScegEJbyyhW4',
    appId: '1:1014202871879:android:6ace78bf40142e01994162',
    messagingSenderId: '1014202871879',
    projectId: 'mayda-nozzle',
    storageBucket: 'mayda-nozzle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeCTjJyA1-SLOlv-e0OGJwTSwmaTuGqEw',
    appId: '1:1014202871879:ios:41307f1ebb768d0e994162',
    messagingSenderId: '1014202871879',
    projectId: 'mayda-nozzle',
    storageBucket: 'mayda-nozzle.appspot.com',
    iosBundleId: 'com.example.maydanozzle',
  );
}
